---
title: "EDA"
author: "Mario Becerra"
date: "October 2017"
output: html_document
---

```{r}
# https://www.kaggle.com/new-york-city/nyc-property-sales
# http://www1.nyc.gov/site/finance/taxes/property-rolling-sales-data.page
# https://www.moveline.com/blog/moving-to-new-york-city-know-your-apartment-terminology
# https://www1.nyc.gov/site/planning/data-maps/open-data/dwn-nynta.page
# https://data.cityofnewyork.us/Business/Zip-Code-Boundaries/i8iw-xf4u/data

library(tidyverse)
library(knitr)
library(utilsMBC)

dat <- read_csv("../data/nyc-rolling-sales.csv",
                na = c("", "NA", "-")) %>% 
  make_names() %>% 
  rename(id = X1)
```

```{r}
dim(dat)

head(dat) %>% 
  kable()

str(dat)

sapply(dat, function(x) sum(is.na(x))) %>% 
  as.data.frame() %>% 
  rownames_to_column() %>% 
  kable()

sum(dat$SALE_PRICE == 0, na.rm = T)

sum(dat$SALE_PRICE > 0, na.rm = T)

sum(dat$SALE_PRICE > 0 & dat$SALE_PRICE < 10000, na.rm = T)

sum(dat$SALE_PRICE < 10000, na.rm = T)

dat_clean = dat %>%
  filter(SALE_PRICE > 7000, 
         !is.na(SALE_PRICE))

dim(dat_clean)

qplot(dat_clean$SALE_PRICE)

qplot(log(dat_clean$SALE_PRICE))

sapply(dat_clean, function(x) sum(is.na(x))) %>% 
  as.data.frame() %>% 
  rownames_to_column() %>% 
  kable()


dat_clean %>% 
  filter(!is.na(LAND_SQUARE_FEET)) %>% 
  dim()

dat_clean %>% 
  filter(!is.na(LAND_SQUARE_FEET)) %>% 
  ggplot() + geom_histogram(aes(LAND_SQUARE_FEET))

dat_clean %>% 
  filter(!is.na(LAND_SQUARE_FEET),
         LAND_SQUARE_FEET > 0) %>% 
  dim()

dat_clean %>% 
  filter(!is.na(LAND_SQUARE_FEET),
         LAND_SQUARE_FEET > 0) %>% 
  ggplot() + 
  geom_histogram(aes(LAND_SQUARE_FEET))

dat_clean %>% 
  filter(!is.na(LAND_SQUARE_FEET),
         LAND_SQUARE_FEET > 0) %>% 
  ggplot() + 
  geom_histogram(aes(log(LAND_SQUARE_FEET)))

sum(dat$LAND_SQUARE_FEET == 0, na.rm = T)

dat_clean2 <- dat_clean %>% 
  filter(!is.na(LAND_SQUARE_FEET),
         LAND_SQUARE_FEET > 0,
         !is.na(GROSS_SQUARE_FEET),
         GROSS_SQUARE_FEET > 0,
         ZIP_CODE != 0) %>% 
  mutate(BOROUGH_NAME = 
           ifelse(BOROUGH == 1, "Manhattan", ifelse(
             BOROUGH == 2, "Bronx", ifelse(
               BOROUGH == 3, "Brooklyn", ifelse(
                 BOROUGH == 4, "Queens", "Staten Island")))
           ),
         Complete_address = paste0(
           ADDRESS, 
           ", ", 
           NEIGHBORHOOD,
           ", ",
           BOROUGH_NAME, 
           ", New York, ", 
           ZIP_CODE, 
           ", USA"))

dat_clean2$BOROUGH %>% table()
dat_clean2$BOROUGH_NAME %>% table()

dat_clean2 %>% 
  ggplot() +
  geom_point(aes(LAND_SQUARE_FEET, SALE_PRICE), size = 0.4, alpha = 0.5)

dat_clean2 %>% 
  ggplot() +
  geom_point(aes(log(LAND_SQUARE_FEET), log(SALE_PRICE)), size = 0.4, alpha = 0.5)

dat_clean2 %>% 
  ggplot() +
  geom_point(aes(log(GROSS_SQUARE_FEET), log(SALE_PRICE)), size = 0.4, alpha = 0.5)


dat_clean2 %>% 
  ggplot() +
  geom_point(aes(log(GROSS_SQUARE_FEET), log(LAND_SQUARE_FEET)), size = 0.4, alpha = 0.5)


dat_clean2 %>% 
  filter(YEAR_BUILT > 0) %>% 
  ggplot() +
  geom_point(aes(YEAR_BUILT, log(SALE_PRICE)), size = 0.4, alpha = 0.5)



dat_clean2 %>% 
  filter(YEAR_BUILT > 0) %>% 
  mutate(PRICE_PER_SQ_FT = SALE_PRICE/GROSS_SQUARE_FEET) %>% 
  ggplot() +
  geom_point(aes(YEAR_BUILT, PRICE_PER_SQ_FT), size = 0.4, alpha = 0.5)

dat_clean2 %>% 
  mutate(PRICE_PER_SQ_FT = SALE_PRICE/GROSS_SQUARE_FEET) %>% 
  ggplot() +
  geom_histogram(aes(PRICE_PER_SQ_FT))

dat_clean2 %>% 
  mutate(PRICE_PER_SQ_FT = SALE_PRICE/GROSS_SQUARE_FEET) %>% 
  ggplot() +
  geom_histogram(aes(log(PRICE_PER_SQ_FT)))

dat_clean2 %>% 
  mutate(PRICE_PER_SQ_FT = SALE_PRICE/GROSS_SQUARE_FEET) %>% 
  filter(PRICE_PER_SQ_FT > 50) %>% 
  ggplot() +
  geom_histogram(aes(x = log(PRICE_PER_SQ_FT), y = ..density..)) +
  facet_wrap(~BOROUGH_NAME)


dat_clean2 %>% 
  mutate(PRICE_PER_SQ_FT = SALE_PRICE/GROSS_SQUARE_FEET) %>% 
  filter(PRICE_PER_SQ_FT > 50) %>% 
  ggplot() +
  geom_boxplot(aes(x = BOROUGH_NAME, y = log(PRICE_PER_SQ_FT))) 

table(dat_clean2$BUILDING_CLASS_AT_TIME_OF_SALE) %>% sort(decreasing = T)

table(dat_clean2$BUILDING_CLASS_CATEGORY) %>% sort(decreasing = T)


dat_clean2 %>% 
  group_by(BUILDING_CLASS_CATEGORY) %>% 
  mutate(num = length(BUILDING_CLASS_CATEGORY)) %>% 
  filter(num > 300) %>% 
  ggplot() +
  geom_point(aes(log(GROSS_SQUARE_FEET), log(SALE_PRICE), color = BUILDING_CLASS_CATEGORY), 
             size = 0.4, alpha = 0.5)

dat_clean2 %>% 
  filter(TAX_CLASS_AT_TIME_OF_SALE == 1 |
           TAX_CLASS_AT_TIME_OF_SALE == 2) %>% 
  ggplot() +
  geom_point(aes(log(GROSS_SQUARE_FEET), log(SALE_PRICE), color = BUILDING_CLASS_CATEGORY), 
             size = 0.7, alpha = 0.9)


dat_clean2$TAX_CLASS_AT_TIME_OF_SALE %>% table()


dat_clean2 %>% 
  group_by(BUILDING_CLASS_CATEGORY) %>% 
  mutate(num = length(BUILDING_CLASS_CATEGORY)) %>% 
  filter(num > 300) %>% 
  .$TAX_CLASS_AT_TIME_OF_SALE %>% 
  table()


dat_clean2 %>% 
  filter(TAX_CLASS_AT_TIME_OF_SALE == 1 |
           TAX_CLASS_AT_TIME_OF_SALE == 2) %>% 
  .$BUILDING_CLASS_CATEGORY %>% 
  table() %>% 
  sort(decreasing = T)

```

# Coords

```{r}
library(rgdal)
library(maptools)
library(gpclib)
gpclibPermit() 


nyc_zip_shape <- readOGR("../data/ZIP_CODE_040114/", layer = "ZIP_CODE_040114") %>% 
  spTransform(CRS("+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0"))

nyc_zip_shape@data$id <- as.character(1:nrow(nyc_zip_shape@data))

nyc_zip_tibble <- fortify(nyc_zip_shape, region = "id") %>% 
  as_tibble() %>% 
  left_join(nyc_zip_shape@data)

nyc_sales <- read_rds("../out/nyc_sales.rds") %>% 
rename(id_sale = id) %>% 
mutate(long = as.numeric(long),
       lat = as.numeric(lat))

nyc_zip_tibble %>% 
  ggplot()+
  geom_path(aes(x = long, y = lat, group = group),
            color = 'black', size = 0.1) +
  coord_fixed() +
  theme_bw()



nyc_zip_tibble %>% 
  ggplot()+
  geom_polygon(aes(x = long, y = lat, group = group),
            fill = 'white', color = 'black', size = 0.1) +
  geom_point(data = nyc_sales,
             aes(x = long, y = lat),
             size = 0.1,
             alpha = 0.5) +
  coord_fixed() +
  theme_bw()






```

